<?php

// bbSolution Application Settings
// Generated by the bbSolution Installation Wizard

// !! EDIT AT YOUR OWN RISK !!

// No hacking attempts are allowed
if ( ! defined( 'BBS' ) )
{
    echo '<h1>Access Denied</h1>You are not allowed to access this file directly.';
    exit();
}

$CFG['db_driver'] = 'pdo_mysql';
$CFG['db_host'] = 'localhost';
$CFG['db_port'] = 3306;
$CFG['db_name'] = 'yourihos_bbs';
$CFG['db_username'] = 'yourihos_sjwspud';
$CFG['db_password'] = '11Meridian7!!';
$CFG['db_prefix'] = 'bbs_';
$CFG['db_persistant'] = false;
$CFG['db_debug_mode'] = true;
$CFG['db_debug_dir'] = 'logs/db';
$CFG['cache_db'] = true;
$CFG['cache_db_method'] = 'filecache'; // filecache or dbcache
$CFG['cache_dir'] = 'cache';
$CFG['cache_db_dir'] = 'db';

?>