<?php

// bbSolution Application Settings
// Generated by the bbSolution Installation Wizard

// !! EDIT AT YOUR OWN RISK !!

// No hacking attempts are allowed
if ( ! defined( 'BBS' ) )
{
    echo '<h1>Access Denied</h1>You are not allowed to access this file directly.';
    exit();
}

$CFG['db_driver'] = 'pdo_mysql';
$CFG['db_host'] = 'localhost';
$CFG['db_port'] = 3306;
$CFG['db_name'] = '';
$CFG['db_username'] = 'root';
$CFG['db_password'] = '';
$CFG['db_prefix'] = 'bbs_';
$CFG['db_persistant'] = false;
$CFG['db_debug_mode'] = false;
$CFG['db_debug_dir'] = 'logs/db';

?>